import crypto from 'node:crypto';
import path from 'node:path';
import type { Database } from 'sql.js';
import { AgentError } from '../../../shared/agent/errors';
import type { CommandResult, EntityRef, QueryResult, TrustedExecutionContext } from '../../../shared/agent/v1/contracts';
import type { AgentCommandEnvelope, AgentQueryEnvelope, JsonObject, OperationDescriptor } from '../../../shared/agent/v1/gatewayContracts';
import { hashCanonicalJson } from '../../../shared/agent/v1/gatewaySchemas';
import type { ImportDraft, ImportDraftChange, ImportDraftIssue, ImportDraftQuestion, ImportDraftValidation, ImportsCommand, ImportsCommandValues, ImportsQuery, ImportsQueryValues } from '../../../shared/imports/v1';
import type { GatewayResolvedState } from '../../agent/agentGateway';
import { createManagedImagePath } from '../../services/fileService';
import { getPaths } from '../../services/pathService';
import { createDatabaseCoordinatorBusinessCapability, type DatabaseCoordinator, type DatabaseTerminalHook } from '../../persistence/databaseCoordinator';
import { createOperationManifest, evidenceForBytes, OperationJournal, OperationManifestStore, type OperationFile, type OperationManifest, type OperationManifestError } from '../../persistence/operationJournal';
import { DomainEventBus } from '../domainEvents';
import type { ReadOnlyDatabaseFacade } from '../queryBus';
import { QuestionRepository, type QuestionImageInsert } from '../questions/questionRepository';
import { importsCommandTypes, importsQueryTypes, validateImportsCommand, validateImportsQuery } from './contracts';
import { managedImportInboxRoot, planUserSelectedImportImages, verifyManagedImportAsset, type ManagedImportAsset } from './managedInbox';

interface DraftRow extends Record<string, unknown> { draft_id: string; owner_client_id: string; state: ImportDraft['state']; source: ImportDraft['provenance']['source']; network_disclosure: ImportDraft['provenance']['networkDisclosure']; created_by: ImportDraft['provenance']['createdBy']; items_json: string; validation_json: string | null; applied_question_ids_json: string; created_at: string; updated_at: string; }
interface AssetRow extends Record<string, unknown> { asset_id: string; owner_client_id: string; file_name: string; file_path: string; sha256: string; size: number; state: 'staged' | 'consumed' | 'cancelled'; created_at: string; updated_at: string; }

export interface ImportsApplication {
  readonly eventBus: DomainEventBus;
  execute<C extends ImportsCommand>(command: C, context: TrustedExecutionContext, terminalHook?: DatabaseTerminalHook<CommandResult<ImportsCommandValues[C['type']]>>): Promise<CommandResult<ImportsCommandValues[C['type']]>>;
  query<Q extends ImportsQuery>(query: Q, context: TrustedExecutionContext): QueryResult<ImportsQueryValues[Q['type']]>;
  resolveState(envelope: AgentCommandEnvelope | AgentQueryEnvelope, descriptor: OperationDescriptor): GatewayResolvedState;
  stageSelectedImages(filePaths: readonly string[], context: TrustedExecutionContext, proof?: { readonly kind: 'main_process_selection' }): Promise<readonly { assetId: string; fileName: string; sha256: string; size: number }[]>;
}

function one<T>(database: Database, sql: string, values: readonly unknown[] = []): T | undefined { const statement = database.prepare(sql); try { statement.bind(values as never); return statement.step() ? statement.getAsObject() as T : undefined; } finally { statement.free(); } }
function safeJson<T>(value: string, label: string): T { try { return JSON.parse(value) as T; } catch { throw new AgentError('RECOVERY_FENCE', { field: label }); } }
function draftFromRow(row: DraftRow): ImportDraft { const items = safeJson<ImportDraftQuestion[]>(row.items_json, 'importDraft.items'); const validation = row.validation_json ? safeJson<ImportDraftValidation>(row.validation_json, 'importDraft.validation') : undefined; const appliedQuestionIds = safeJson<number[]>(row.applied_question_ids_json, 'importDraft.appliedQuestionIds'); return Object.freeze({ schemaVersion: 1, draftId: row.draft_id, ownerClientId: row.owner_client_id, state: row.state, provenance: Object.freeze({ source: row.source, networkDisclosure: row.network_disclosure, createdBy: row.created_by }), items: Object.freeze(items.map((item) => Object.freeze({ ...item, tags: Object.freeze([...item.tags]), knowledgePoints: Object.freeze([...item.knowledgePoints]), images: Object.freeze(item.images.map((image) => Object.freeze({ ...image }))) }))), ...(validation ? { validation: Object.freeze(validation) } : {}), appliedQuestionIds: Object.freeze(appliedQuestionIds), createdAt: row.created_at, updatedAt: row.updated_at }); }
function requireOwnedDraft(database: Database, draftId: string, context: TrustedExecutionContext): ImportDraft { const row = one<DraftRow>(database, 'SELECT * FROM import_drafts WHERE draft_id = ?', [draftId]); if (!row) throw new AgentError('HANDLER_NOT_FOUND'); if (row.owner_client_id !== context.client.clientId && context.source !== 'renderer') throw new AgentError('SCOPE_DENIED'); return draftFromRow(row); }
function readAsset(database: Database, assetId: string, context: TrustedExecutionContext): AssetRow { const asset = one<AssetRow>(database, 'SELECT * FROM import_managed_assets WHERE asset_id = ?', [assetId]); if (!asset) throw new AgentError('HANDLER_NOT_FOUND'); if (asset.owner_client_id !== context.client.clientId && context.source !== 'renderer') throw new AgentError('SCOPE_DENIED'); return asset; }
function contentHash(item: ImportDraftQuestion): string { return hashCanonicalJson({ title: item.title.trim(), content: item.content.trim(), answer: item.answer.trim(), subject: item.subject, category: item.category.trim(), questionType: item.questionType.trim() }); }

function calculateValidation(draft: ImportDraft, database: { select(sql: string, values?: readonly unknown[]): readonly Record<string, unknown>[] }): ImportDraftValidation {
  const issues: ImportDraftIssue[] = []; const changes: ImportDraftChange[] = []; const seenContent = new Set<string>(); const seenAssets = new Set<string>();
  for (const item of draft.items) {
    if (!item.title.trim()) issues.push({ itemId: item.itemId, field: 'title', code: 'required', message: 'Title is required.' });
    if (!item.content.trim() && !item.images.some((image) => image.role === 'question')) issues.push({ itemId: item.itemId, field: 'content', code: 'required', message: 'Question content or a question image is required.' });
    for (const image of item.images) { if (seenAssets.has(image.assetId)) issues.push({ itemId: item.itemId, field: 'images', code: 'duplicate_asset', message: 'A managed image may be bound only once.' }); seenAssets.add(image.assetId); }
    const hash = contentHash(item);
    const duplicateInDraft = seenContent.has(hash); seenContent.add(hash);
    const duplicateStored = database.select('SELECT id FROM questions WHERE title = ? AND content = ? AND answer = ? ORDER BY id LIMIT 1', [item.title.trim(), item.content.trim(), item.answer.trim()]).length > 0;
    changes.push({ itemId: item.itemId, action: duplicateInDraft || duplicateStored ? 'skip_duplicate' : 'create', contentHash: hash, imageCount: item.images.length });
  }
  issues.sort((left, right) => `${left.itemId}\0${left.field}\0${left.code}`.localeCompare(`${right.itemId}\0${right.field}\0${right.code}`));
  changes.sort((left, right) => left.itemId.localeCompare(right.itemId));
  const validationHash = hashCanonicalJson({ issues, changes });
  const previewHash = hashCanonicalJson({ schemaVersion: 1, draftId: draft.draftId, provenance: draft.provenance, changes, validationHash });
  return Object.freeze({ valid: issues.length === 0, issues: Object.freeze(issues), changes: Object.freeze(changes), validationHash, previewHash });
}

function operationError(error: unknown, phase: string): OperationManifestError { return { code: error instanceof AgentError ? error.code : 'import_draft_file_operation_failed', phase, message: error instanceof Error ? error.message.slice(0, 1_000) : 'Import draft file operation failed' }; }
function journalStore(): OperationManifestStore { return new OperationManifestStore(path.normalize(path.join(getPaths().data, 'operation-journal'))); }
function journal(): OperationJournal { return new OperationJournal(journalStore()); }

async function finalizeManifest(coordinator: DatabaseCoordinator, manifest: OperationManifest | undefined, succeeded: boolean): Promise<void> {
  if (!manifest) return; const store = journalStore(); const operationJournal = journal(); const latest = await store.read(manifest.operationId) ?? manifest;
  try { if (succeeded) await operationJournal.commitFiles(await operationJournal.markDatabaseCommitted(latest)); else if (coordinator.state === 'writable') await operationJournal.compensate(latest, operationError(new Error('Database command did not commit'), 'database_command')); else await operationJournal.needsRecovery(latest, operationError(new Error('Database outcome is ambiguous'), 'database_command')); }
  catch (error) { const current = await store.read(manifest.operationId) ?? latest; await operationJournal.needsRecovery(current, operationError(error, 'file_finalization')).catch(() => undefined); if (coordinator.state === 'writable') { const lease = await coordinator.beginMaintenance(); coordinator.finishMaintenance(lease, 'needs_recovery'); } throw error; }
}

function toQuestionInput(item: ImportDraftQuestion, batchId: string) { return { title: item.title.trim(), content: item.content.trim(), wrong_thinking: item.wrongThinking.trim(), wrong_solution: item.wrongThinking.trim(), correct_solution: item.correctSolution.trim(), answer: item.answer.trim(), subject: item.subject, category: item.category.trim(), question_type: item.questionType.trim(), error_reason: item.errorReason.trim(), source: item.source.trim(), difficulty: item.difficulty, mastery_level: item.masteryLevel, note: '', tags: [...item.tags], questionImageSources: [], solutionImageSources: [], import_batch_id: batchId }; }

export function registerImports(options: { coordinator: DatabaseCoordinator; readOnlyDatabase: ReadOnlyDatabaseFacade; now?: () => string; randomUUID?: () => string }): ImportsApplication {
  const capability = createDatabaseCoordinatorBusinessCapability(options.coordinator); const eventBus = new DomainEventBus(); const now = options.now ?? (() => new Date().toISOString()); const uuid = options.randomUUID ?? crypto.randomUUID;
  const resolveState = (envelope: AgentCommandEnvelope | AgentQueryEnvelope, descriptor: OperationDescriptor): GatewayResolvedState => {
    if (descriptor.domain !== 'imports' || descriptor.name !== envelope.operation) throw new Error('Imports Gateway descriptor mismatch');
    const draftId = typeof envelope.payload.draftId === 'string' ? envelope.payload.draftId : undefined; const entities: EntityRef[] = [];
    let affectedEntityCount = 1; let managedFileCount = 0;
    if (draftId) { entities.push({ entityType: 'import_draft', entityId: draftId }); const row = options.readOnlyDatabase.select<DraftRow>('SELECT * FROM import_drafts WHERE draft_id = ?', [draftId])[0]; if (row) { const draft = draftFromRow(row); if (envelope.operation === 'imports.apply_draft' || envelope.operation === 'imports.validate_draft') affectedEntityCount = draft.items.length; managedFileCount = draft.items.reduce((sum, item) => sum + item.images.length, 0); } else affectedEntityCount = 0; }
    else { const items = Array.isArray(envelope.payload.items) ? envelope.payload.items : []; affectedEntityCount = items.length; entities.push({ entityType: 'import_draft_create', entityId: hashCanonicalJson(envelope.payload) }); }
    const affectedEntities = Object.freeze(entities); return Object.freeze({ affectedEntityCount, affectedEntities, affectedSetHash: hashCanonicalJson(affectedEntities), targetHash: hashCanonicalJson({ operation: envelope.operation, affectedEntities, managedFileCount } as unknown as JsonObject), dataVersion: Object.freeze({ ...options.coordinator.currentVersion() }), managedFileCount });
  };

  const execute = async <C extends ImportsCommand>(command: C, context: TrustedExecutionContext, terminalHook?: DatabaseTerminalHook<CommandResult<ImportsCommandValues[C['type']]>>): Promise<CommandResult<ImportsCommandValues[C['type']]>> => {
    validateImportsCommand(command); let manifest: OperationManifest | undefined; let eventDraft: { type: string; payload: Record<string, unknown> } | undefined; let databaseCommitted = false;
    try {
      const terminal = await options.coordinator.executeBusinessWrite<unknown, CommandResult>(capability, { requestId: context.requestId, concurrency: context.concurrency, expectedVersion: context.expectedVersion, terminalHook: terminalHook as DatabaseTerminalHook<CommandResult> | undefined,
        async execute(database, scope) {
          const timestamp = now();
          if (command.type === 'imports.create_draft') { const draftId = `draft-${uuid().toLowerCase()}`; const items = command.payload.items.map((item) => ({ ...item, images: [] })); database.run('INSERT INTO import_drafts (draft_id,owner_client_id,state,source,network_disclosure,created_by,items_json,validation_json,applied_question_ids_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,NULL,\'[]\',?,?)', [draftId, context.client.clientId, 'collecting', command.payload.source, command.payload.networkDisclosure, context.source, JSON.stringify(items), timestamp, timestamp]); eventDraft = { type: 'imports.draft_created', payload: { draftId } }; return { changed: true, value: draftFromRow(one<DraftRow>(database, 'SELECT * FROM import_drafts WHERE draft_id = ?', [draftId])!) };
          }
          const draft = requireOwnedDraft(database, command.payload.draftId, context);
          if (command.type === 'imports.add_draft_image') { if (draft.state !== 'collecting') throw new AgentError('VALIDATION_ERROR', { field: 'draft.state' }); const asset = readAsset(database, command.payload.assetId, context); if (asset.state !== 'staged') throw new AgentError('VALIDATION_ERROR', { field: 'assetId' }); await verifyManagedImportAsset({ assetId: asset.asset_id, fileName: asset.file_name, filePath: asset.file_path, sha256: asset.sha256, size: asset.size }); const items = draft.items.map((item) => item.itemId === command.payload.itemId ? { ...item, images: [...item.images, { assetId: asset.asset_id, role: command.payload.role }] } : item); if (!items.some((item) => item.itemId === command.payload.itemId)) throw new AgentError('HANDLER_NOT_FOUND'); if (items.flatMap((item) => item.images).filter((image) => image.assetId === asset.asset_id).length > 1) throw new AgentError('VALIDATION_ERROR', { field: 'assetId' }); database.run('UPDATE import_drafts SET items_json=?, validation_json=NULL, updated_at=? WHERE draft_id=?', [JSON.stringify(items), timestamp, draft.draftId]); eventDraft = { type: 'imports.draft_image_added', payload: { draftId: draft.draftId, assetId: asset.asset_id } }; return { changed: true, value: draftFromRow(one<DraftRow>(database, 'SELECT * FROM import_drafts WHERE draft_id = ?', [draft.draftId])!) };
          }
          if (command.type === 'imports.validate_draft') { if (!['collecting', 'validated'].includes(draft.state)) throw new AgentError('VALIDATION_ERROR', { field: 'draft.state' }); const validation = calculateValidation(draft, { select: (sql, values) => { const statement = database.prepare(sql); try { statement.bind([...(values ?? [])] as never); const rows: Record<string, unknown>[] = []; while (statement.step()) rows.push(statement.getAsObject()); return rows; } finally { statement.free(); } } }); database.run('UPDATE import_drafts SET state=?, validation_json=?, updated_at=? WHERE draft_id=?', [validation.valid ? 'validated' : 'collecting', JSON.stringify(validation), timestamp, draft.draftId]); eventDraft = { type: 'imports.draft_validated', payload: { draftId: draft.draftId, valid: validation.valid } }; return { changed: true, value: validation };
          }
          if (command.type === 'imports.cancel') { if (draft.state === 'applied' || draft.state === 'cancelled') throw new AgentError('VALIDATION_ERROR', { field: 'draft.state' }); const assetIds = [...new Set(draft.items.flatMap((item) => item.images.map((image) => image.assetId)))]; const files: OperationFile[] = []; for (const assetId of assetIds) { const asset = readAsset(database, assetId, context); await verifyManagedImportAsset({ assetId: asset.asset_id, fileName: asset.file_name, filePath: asset.file_path, sha256: asset.sha256, size: asset.size }); files.push({ fileId: assetId, kind: 'quarantine_delete', targetPath: asset.file_path, quarantinePath: path.normalize(path.join(getPaths().data, 'import-inbox', 'quarantine', `${context.requestId}-${assetId}.quarantine`)), content: { sha256: asset.sha256, size: asset.size }, status: 'pending' }); }
            if (files.length) { const before = options.coordinator.currentVersion(); manifest = createOperationManifest({ operationId: context.requestId, requestId: context.requestId, commandType: command.type, source: context.source, clientId: context.client.clientId, traceId: context.traceId, inputHash: crypto.createHash('sha256').update(JSON.stringify(command)).digest('hex'), storage: 'data_root', versionBefore: before, versionAfter: { dataEpoch: before.dataEpoch, dataRevision: before.dataRevision + 1 }, affectedEntities: [{ entityType: 'import_draft', entityId: draft.draftId }], roots: { manifestRoot: journalStore().root, managedRoots: [path.normalize(getPaths().root)], sourceRoots: [managedImportInboxRoot()] }, files, createdAt: timestamp }); manifest = await journal().stage(await journal().prepare(manifest)); }
            for (const assetId of assetIds) database.run("UPDATE import_managed_assets SET state='cancelled',updated_at=? WHERE asset_id=?", [timestamp, assetId]); database.run("UPDATE import_drafts SET state='cancelled',updated_at=? WHERE draft_id=?", [timestamp, draft.draftId]); eventDraft = { type: 'imports.draft_cancelled', payload: { draftId: draft.draftId } }; return { changed: true, value: { draftId: draft.draftId, cancelled: true as const } };
          }
          if (draft.state !== 'validated' || !draft.validation?.valid || draft.validation.previewHash !== command.payload.previewHash) throw new AgentError('DATA_REVISION_CONFLICT');
          const batchId = `wrong_questions-${uuid().toLowerCase()}`; database.run("INSERT INTO import_batches (id,owner_client_id,type,name,source_file_name,source,imported_at,item_count,asset_count,status,metadata_json,deleted_at) VALUES (?,?,'wrong_questions',?,'',?,?,0,0,'active',?,NULL)", [batchId, context.client.clientId, `Draft ${draft.draftId}`, draft.provenance.source, timestamp, JSON.stringify({ schemaVersion: 1, draftId: draft.draftId, previewHash: draft.validation.previewHash, provenance: draft.provenance })]);
          const repository = new QuestionRepository(database, scope, options.now); const createdQuestionIds: number[] = []; const skippedItemIds = draft.validation.changes.filter((change) => change.action === 'skip_duplicate').map((change) => change.itemId); const files: OperationFile[] = []; const imageRows: { questionId: number; image: QuestionImageInsert; targetPath: string; asset: AssetRow }[] = [];
          for (const change of draft.validation.changes) { if (change.action !== 'create') continue; const item = draft.items.find((candidate) => candidate.itemId === change.itemId)!; let question = repository.create(toQuestionInput(item, batchId)); const bindings: QuestionImageInsert[] = []; for (const [index, binding] of item.images.entries()) { const asset = readAsset(database, binding.assetId, context); await verifyManagedImportAsset({ assetId: asset.asset_id, fileName: asset.file_name, filePath: asset.file_path, sha256: asset.sha256, size: asset.size }); const imageType = binding.role === 'question' ? 'original' as const : 'solution' as const; const destination = createManagedImagePath(question.id, imageType, asset.file_path, `${context.requestId}-${asset.asset_id}`); files.push({ fileId: `copy-${files.length + 1}`, kind: 'create', sourcePath: asset.file_path, targetPath: destination.absolutePath, stagingPath: path.normalize(path.join(getPaths().images, '.import-draft-operations', 'staging', `${context.requestId}-${index}-${asset.asset_id}.stage`)), content: { sha256: asset.sha256, size: asset.size }, status: 'pending' }); const image = { imageType, filePath: destination.storedPath }; bindings.push(image); imageRows.push({ questionId: question.id, image, targetPath: destination.absolutePath, asset }); }
            if (bindings.length) question = repository.update(question.id, toQuestionInput(item, batchId), bindings).question; const knownNodes = item.knowledgePoints.filter((nodeId) => one<{ node_id: string }>(database, 'SELECT node_id FROM knowledge_points WHERE node_id = ?', [nodeId])); if (knownNodes.length) repository.linkKnowledgePoints(question.id, knownNodes, 'gpt'); createdQuestionIds.push(question.id); database.run("INSERT INTO import_batch_items (batch_id,target_table,target_id,action,created_at) VALUES (?,'questions',?,'created',?)", [batchId, String(question.id), timestamp]); }
          if (files.length) { const before = options.coordinator.currentVersion(); manifest = createOperationManifest({ operationId: context.requestId, requestId: context.requestId, commandType: command.type, source: context.source, clientId: context.client.clientId, traceId: context.traceId, inputHash: crypto.createHash('sha256').update(JSON.stringify(command)).digest('hex'), storage: 'data_root', versionBefore: before, versionAfter: { dataEpoch: before.dataEpoch, dataRevision: before.dataRevision + 1 }, affectedEntities: [{ entityType: 'import_draft', entityId: draft.draftId }, ...createdQuestionIds.map((id) => ({ entityType: 'question', entityId: String(id) }))], roots: { manifestRoot: journalStore().root, managedRoots: [path.normalize(getPaths().root)], sourceRoots: [managedImportInboxRoot()] }, files, createdAt: timestamp }); manifest = await journal().stage(await journal().prepare(manifest)); }
          for (const entry of imageRows) database.run("INSERT INTO import_assets (batch_id,asset_type,file_path,created_at,deleted_at) VALUES (?,'question_image',?,?,NULL)", [batchId, entry.targetPath, timestamp]); if (imageRows.length) database.run(`UPDATE import_managed_assets SET state='consumed',updated_at=? WHERE asset_id IN (${[...new Set(imageRows.map((entry) => entry.asset.asset_id))].map(() => '?').join(',')})`, [timestamp, ...new Set(imageRows.map((entry) => entry.asset.asset_id))]); database.run('UPDATE import_batches SET item_count=?,asset_count=? WHERE id=?', [createdQuestionIds.length, imageRows.length, batchId]); database.run("UPDATE import_drafts SET state='applied',applied_question_ids_json=?,updated_at=? WHERE draft_id=?", [JSON.stringify(createdQuestionIds), timestamp, draft.draftId]); eventDraft = { type: 'imports.draft_applied', payload: { draftId: draft.draftId, questionIds: createdQuestionIds } }; return { changed: createdQuestionIds.length > 0 || skippedItemIds.length > 0, value: { draftId: draft.draftId, createdQuestionIds: Object.freeze(createdQuestionIds), skippedItemIds: Object.freeze(skippedItemIds), previewHash: draft.validation.previewHash } };
        },
        finalizeValue(value) { const events = value.semanticChanged && eventDraft ? eventBus.finalizeEvents(eventBus.prepareEvents([eventDraft], { requestId: context.requestId, traceId: context.traceId, source: context.source }), { versionBefore: value.versionBefore, versionAfter: value.versionAfter }) : []; return Object.freeze({ changed: value.semanticChanged, value: value.value, events, dataVersion: Object.freeze({ ...value.versionAfter }) }); }
      });
      databaseCommitted = true; await finalizeManifest(options.coordinator, manifest, true); await eventBus.publish(terminal.value.events); return terminal.value as CommandResult<ImportsCommandValues[C['type']]>;
    } catch (error) { if (!databaseCommitted) await finalizeManifest(options.coordinator, manifest, false); throw error; }
  };

  return Object.freeze({ eventBus, execute,
    query<Q extends ImportsQuery>(query: Q, context: TrustedExecutionContext) { validateImportsQuery(query); if (options.coordinator.state === 'needs_recovery' || options.coordinator.pendingWrites !== 0) throw new AgentError('RECOVERY_FENCE'); const before = options.coordinator.currentVersion(); const rows = options.readOnlyDatabase.select<DraftRow>('SELECT * FROM import_drafts WHERE draft_id = ?', [query.payload.draftId]); if (!rows[0]) throw new AgentError('HANDLER_NOT_FOUND'); if (rows[0].owner_client_id !== context.client.clientId && context.source !== 'renderer') throw new AgentError('SCOPE_DENIED'); const draft = draftFromRow(rows[0]); const value = query.type === 'imports.get' ? draft : (draft.validation ?? calculateValidation(draft, { select: (sql, values) => options.readOnlyDatabase.select(sql, values as never) })); const after = options.coordinator.currentVersion(); if (before.dataEpoch !== after.dataEpoch || before.dataRevision !== after.dataRevision) throw new AgentError('MAINTENANCE_FENCE'); return { value, dataVersion: Object.freeze({ ...after }) } as QueryResult<ImportsQueryValues[Q['type']]>; },
    resolveState,
    async stageSelectedImages(filePaths: readonly string[], context: TrustedExecutionContext, proof?: { readonly kind: 'main_process_selection' }) {
      if (context.source === 'mcp') throw new AgentError('SCOPE_DENIED');
      if (context.source === 'renderer' && proof?.kind !== 'main_process_selection') throw new AgentError('SCOPE_DENIED');
      const assets = await planUserSelectedImportImages(filePaths);
      let manifest: OperationManifest | undefined;
      let databaseCommitted = false;
      try {
        const before = options.coordinator.currentVersion();
        const timestamp = now();
        manifest = createOperationManifest({ operationId: context.requestId, requestId: context.requestId, commandType: 'imports.stage_selected_images', source: context.source, clientId: context.client.clientId, traceId: context.traceId,
          inputHash: crypto.createHash('sha256').update(JSON.stringify(assets.map((asset) => ({ fileName: asset.fileName, sha256: asset.sha256, size: asset.size })))).digest('hex'), storage: 'data_root',
          versionBefore: before, versionAfter: { dataEpoch: before.dataEpoch, dataRevision: before.dataRevision + 1 }, affectedEntities: assets.map((asset) => ({ entityType: 'import_managed_asset', entityId: asset.assetId })),
          roots: { manifestRoot: journalStore().root, managedRoots: [path.normalize(getPaths().root)], sourceRoots: [...new Set(assets.map((asset) => asset.sourceRoot))] },
          files: assets.map((asset): OperationFile => ({ fileId: asset.assetId, kind: 'create', sourcePath: asset.sourcePath, targetPath: asset.filePath, stagingPath: asset.stagingPath, content: { sha256: asset.sha256, size: asset.size }, status: 'pending' })), createdAt: timestamp });
        manifest = await journal().stage(await journal().prepare(manifest));
        await options.coordinator.executeBusinessWrite(capability, { requestId: context.requestId, concurrency: context.concurrency, expectedVersion: context.expectedVersion, execute(database) { const committedAt = now(); for (const asset of assets) database.run("INSERT INTO import_managed_assets (asset_id,owner_client_id,file_name,file_path,sha256,size,state,created_at,updated_at) VALUES (?,?,?,?,?,?,'staged',?,?)", [asset.assetId, context.client.clientId, asset.fileName, asset.filePath, asset.sha256, asset.size, committedAt, committedAt]); return { changed: assets.length > 0, value: undefined }; } });
        databaseCommitted = true; await finalizeManifest(options.coordinator, manifest, true);
      } catch (error) {
        if (!databaseCommitted) {
          try { await finalizeManifest(options.coordinator, manifest, false); } catch { /* preserve the causal staging error while fencing recovery */ }
        }
        throw error;
      }
      return Object.freeze(assets.map(({ filePath: _filePath, sourcePath: _sourcePath, stagingPath: _stagingPath, sourceRoot: _sourceRoot, ...asset }) => Object.freeze(asset)));
    }
  });
}

export function isImportsCommandOperation(operation: string): boolean { return (importsCommandTypes as readonly string[]).includes(operation); }
export function isImportsQueryOperation(operation: string): boolean { return (importsQueryTypes as readonly string[]).includes(operation); }
