import { execFile } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { promisify } from 'node:util';
import type { DirectHttpsAuthority } from '../../../shared/mcp/v1/oauthContracts';

const execFileAsync = promisify(execFile);

export interface LocalHttpsCertificate { readonly pfx: Uint8Array; readonly passphrase: string; readonly thumbprint: string; readonly notAfter: string; readonly dnsNames: readonly ['localhost']; readonly ipAddresses: readonly ['127.0.0.1']; }
export interface LocalHttpsCertificateIssuer { issue(input: { readonly authority: DirectHttpsAuthority; readonly rootThumbprint: string; readonly rootKeyName: string }): Promise<LocalHttpsCertificate>; }

function safeThumbprint(value: string): string { if (!/^[0-9a-f]{40,128}$/i.test(value)) throw new TypeError('Invalid root certificate thumbprint'); return value.toUpperCase(); }
class PowerShellLocalHttpsCertificateIssuer implements LocalHttpsCertificateIssuer {
  async issue(input: { readonly authority: DirectHttpsAuthority; readonly rootThumbprint: string; readonly rootKeyName: string }): Promise<LocalHttpsCertificate> {
    const rootThumbprint = safeThumbprint(input.rootThumbprint); const passphrase = randomBytes(32).toString('base64url'); const serial = randomBytes(16).toString('base64');
    const script = "$ErrorActionPreference='Stop'; $t=$env:KAOYAN_HTTP_ROOT_THUMBPRINT; $n=$env:KAOYAN_HTTP_CNG_KEY; $p=[Security.Cryptography.CngProvider]::MicrosoftSoftwareKeyStorageProvider; $root=@(Get-ChildItem -Path Cert:\\CurrentUser\\My | Where-Object {$_.Thumbprint -eq $t}); if($root.Count -ne 1 -or -not $root[0].HasPrivateKey){throw 'exact root missing'}; $key=[Security.Cryptography.CngKey]::Open($n,$p); try {$rootRsa=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($root[0]); if($rootRsa -isnot [Security.Cryptography.RSACng] -or $rootRsa.Key.Provider.Provider -ne $p.Provider -or $rootRsa.Key.UniqueName -ne $key.UniqueName){throw 'root key association mismatch'}; $leafKey=[Security.Cryptography.RSA]::Create(2048); try {$req=[Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=localhost',$leafKey,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1); $req.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509BasicConstraintsExtension]::new($false,$false,0,$true)); $req.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509KeyUsageExtension]::new([Security.Cryptography.X509Certificates.X509KeyUsageFlags]::DigitalSignature -bor [Security.Cryptography.X509Certificates.X509KeyUsageFlags]::KeyEncipherment,$true)); $oids=[Security.Cryptography.OidCollection]::new(); [void]$oids.Add([Security.Cryptography.Oid]::new('1.3.6.1.5.5.7.3.1')); $req.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension]::new($oids,$true)); $san=[Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder]::new(); $san.AddDnsName('localhost'); $san.AddIpAddress([Net.IPAddress]::Parse('127.0.0.1')); $req.CertificateExtensions.Add($san.Build($true)); $issued=$req.Create($root[0],(Get-Date).ToUniversalTime().AddMinutes(-1),(Get-Date).ToUniversalTime().AddDays(7),[Convert]::FromBase64String($env:KAOYAN_HTTP_LEAF_SERIAL)); try {$leaf=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::CopyWithPrivateKey($issued,$leafKey); try {$bytes=$leaf.Export([Security.Cryptography.X509Certificates.X509ContentType]::Pfx,$env:KAOYAN_HTTP_PFX_PASSPHRASE); @{thumbprint=$leaf.Thumbprint;notAfter=$leaf.NotAfter.ToUniversalTime().ToString('o');pfx=[Convert]::ToBase64String($bytes)}|ConvertTo-Json -Compress} finally {$leaf.Dispose()}} finally {$issued.Dispose()}} finally {$leafKey.Dispose();$rootRsa.Dispose()}} finally {$key.Dispose()}";
    const result = await execFileAsync('pwsh.exe', ['-NoProfile', '-NonInteractive', '-Command', script], { windowsHide: true, timeout: 30_000, maxBuffer: 128 * 1024, env: { ...process.env, KAOYAN_HTTP_ROOT_THUMBPRINT: rootThumbprint, KAOYAN_HTTP_CNG_KEY: input.rootKeyName, KAOYAN_HTTP_PFX_PASSPHRASE: passphrase, KAOYAN_HTTP_LEAF_SERIAL: serial } });
    let parsed: unknown; try { parsed = JSON.parse(String(result.stdout).trim()); } catch { throw new Error('Local HTTPS certificate issuance failed'); } const value = parsed as Record<string, unknown>; if (typeof value.pfx !== 'string' || typeof value.thumbprint !== 'string' || typeof value.notAfter !== 'string') throw new Error('Local HTTPS certificate metadata is invalid'); const pfx = Buffer.from(value.pfx, 'base64'); if (pfx.length < 32) throw new Error('Local HTTPS certificate is empty'); return Object.freeze({ pfx, passphrase, thumbprint: safeThumbprint(value.thumbprint), notAfter: new Date(value.notAfter).toISOString(), dnsNames: ['localhost'] as const, ipAddresses: ['127.0.0.1'] as const });
  }
}

export async function issueLocalHttpsCertificate(input: { readonly authority: DirectHttpsAuthority; readonly rootThumbprint: string; readonly rootKeyName: string }, issuer: LocalHttpsCertificateIssuer = new PowerShellLocalHttpsCertificateIssuer()): Promise<LocalHttpsCertificate> {
  if (input.authority.resource !== `${input.authority.authority}/mcp` || input.authority.issuer !== input.authority.authority) throw new Error('Local HTTPS authority is invalid');
  return issuer.issue(input);
}
